version: '3.9'

services:
  djangoapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-djangoapi
    ports:
      - 8000:8000
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
